# -*- coding: utf-8 -*-
"""states&capitalsquizipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I7VyUUO7oey2G1AKCSXi9-j5QOTZZWUu
"""

import random as rnd


def getstatescapitals():
    statescapitals = {'mississippi': 'jackson', 'arizona': 'phoenix', 'iowa': 'desmoines',
'massachuettes': 'boston', 'michigan': 'lansing', 'virginia': 'richmond',
'oregon': 'salem', 'hawaii': 'honolulu', 'nebraska': 'lincoln',
'indiana': 'indianapolis', 'ohio': 'columbus', 'illnois': 'springfield'}
    return statescapitals


def main():
    print("states capitals Quiz\n")
    statescapitals = getstatescapitals()
    numberofcorrectanswers = 0
    while True:
        states = list(statescapitals.keys())
        state = rnd.choice(states)
        capital = statescapitals[state]
        # del statescapitals[state]
        # if len(statescapitals) == 0:
        #   break
        # else:
        #   continue
        #  del function if as an comment: name of states may repeat
        #  if not as an comment, name of states won't repeat but the code will end with an error:
        # IndexError: Cannot choose from an empty sequence
        answer = input("what is the capital of "+state+"?")
        if answer.lower() == capital.lower():
            print("correct!")
            numberofcorrectanswers += 1

        else:
            print("incorrect")
            break
        print("\nGame over! you got ", numberofcorrectanswers, "right")



main()